---
title: "Replication file for the paper: A multidimensional feasibility evaluation of low-carbon scenarios"
output:
html_document: default
always_allow_html: true
---
  
  ```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(global.par = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r functions, include=FALSE, MESSAGE=FALSE}
#one of the main functions used to compute the geometric mean

geom_mean<-function(x){exp(mean(log(x)))}
```


```{r packages, include=FALSE, MESSAGE=FALSE}
pkgs<-c("vroom", "tidyverse", "plotly", "RColorBrewer", "viridis", "hrbrthemes", "here", "ggridges", "ggsci", "stringr", "cowplot","scales", "skimr", "jtools", "countrycode", "ggpmisc", "reticulate", "ggrepel")
#install.packages(pkgs) -> please uncomment it if you don't have the required packages installed

load<-lapply(pkgs, library, character.only=TRUE)
```

## Data preparation


```{python pyam_world_data}
#You can import the 1.5C dataset either by using a python package pyam (and the link through reticulate) or by loading it (Release 2.0) from the scenario explorer and saving it in the input folder 

#For this replication file the data was already prepare and is in the input folder

import pyam

df =pyam.read_iiasa(
    'IXSE_SR15',
    model='*',
    variable=["AR5 climate diagnostics|Temperature|Global Mean|MAGICC6|MED",
  "Emissions|CO2",
  "GDP|PPP",
  "Population",
  "Investment|Energy Supply",
  "Investment|Energy Supply|Electricity",
  "Investment|Energy Supply|Electricity|Solar",
  "Investment|Energy Supply|Electricity|Wind",
  "Investment|Energy Supply|Electricity|Nuclear",
  "Investment|Energy Supply|Electricity|Transmission and Distribution",
  "Investment|Energy Supply|Electricity|Biomass|w/ CCS",
  "Investment|Energy Supply|Electricity|Coal|w/ CCS",
  "Capacity|Electricity|Coal",
  "Secondary Energy|Electricity|Coal",
  "Capacity|Electricity|Gas",
  "Capacity|Electricity|Wind",
  "Capacity|Electricity|Solar",
  "Capacity|Electricity|Biomass",
  "Primary Energy|Biomass",
  "Primary Energy|Solar",
  "Secondary Energy|Electricity|Wind",
  "Secondary Energy|Electricity|Gas",
  "Primary Energy|Oil",
  "Price|Primary Energy|Oil",
  "Price|Carbon",
  "Price|Secondary Energy|Electricity",
  "Secondary Energy|Electricity",
  "Secondary Energy|Electricity|Oil",
  "Secondary Energy|Electricity|Nuclear",
  "Secondary Energy|Electricity|Wind",
  "Secondary Energy|Electricity|Solar",
  "Secondary Energy|Electricity|Hydro",
  "Secondary Energy|Electricity|Biomass",
  "Secondary Energy|Electricity|Biomass|w/ CCS",
  "Secondary Energy|Electricity|Coal|w/ CCS",
  "Secondary Energy|Electricity|Gas|w/ CCS",
  "Secondary Energy|Electricity|Oil|w/ CCS",
  "Final Energy|Transportation",
  "Final Energy|Transportation|Electricity",
  "Final Energy|Transportation|Liquids|Biomass",
  "Land Cover",
  "Land Cover|Forest",
  "Land Cover|Cropland",
  "Land Cover|Pasture",
  "Carbon Sequestration|Land Use",
  "Final Energy",
  "Final Energy|Residential and Commercial",
  "Final Energy|Industry",
  "Food Demand",
  "Food Demand|Livestock",
  "Final Energy|Industry|Electricity",
  "Final Energy|Residential and Commercial|Electricity",
  "Price|Agriculture|Livestock|Index",
  "Price|Agriculture|Corn|Index",
  "Emissions|NOx"],
   region='World'
)

df.to_csv('input/full.csv')

```

```{python pyam_region_data}
#You can import the 1.5C dataset either by using a python package pyam (and the link through reticulate) or by loading an .csv file (Release 2.0) from the scenario explorer and saving it in the input folder 


#For this replication file the data was already prepare and is in the input folder


import pyam

df2 =pyam.read_iiasa(
    'IXSE_SR15',
    model='*',
    variable=[
  "Emissions|CO2",
  "GDP|PPP",
  "Population"]
)

df2.to_csv('input/region.csv')
```


```{r data_input, include=FALSE, MESSAGE=FALSE}
#Data from the 1.5C scenario explorer

world<-vroom(here("input", "full.csv"))
region<-vroom(here("input", "region.csv"))
meta<-vroom(here("input", "meta.csv"))
marker_set<-vroom(here("input", "marker.csv"))
meta_policy<-vroom(here("input", "meta_policy.csv"))
baselines<-vroom(here("input", "baselines.csv"))

#assumptions about thresholds

thresholds<-vroom(here("input", "thresholds.csv"))


#Regional conversions for R5 for the empirical data that is used
region_con<-vroom(here("input", "region_conversion.csv"))

#Data on coal from Global Monitor: https://globalenergymonitor.org/projects/global-coal-plant-tracker/ 

coal_50_all<-vroom(here("input", "coal_50_all.csv"))

#Data from Adrijevic et al.(2019, 2020) and the Wittgenstein Center

governance_proj<-vroom(here("input", "governance.csv"))
gov_eff<-vroom(here("input", "gov_eff_projections.csv"))
GII<-vroom(here("input", "GII.csv"))
EPI<-vroom(here("input", "EPI.csv"))
gov_his<-vroom(here("input", "gov_historical.csv"))
age<-vroom(here("input", "age.csv"))
education<-vroom(here("input", "education.csv"))
fertility<-vroom(here("input", "fertility.csv"))
```




```{r data_preparation, include=FALSE, MESSAGE=FALSE}

#here we prepare some transformations for the generation of the indicators


#We look only at data per decade
years<-c("2010", "2020", "2030", "2040", "2050", "2060", "2070", "2080", "2090", "2100")


#Different climate categories
below_1.5<-c("1.5C high overshoot", "1.5C low overshoot", "Below 1.5C")
below_2<-c("Higher 2C", "Lower 2C")


#prepare thresholds

thresholds<-thresholds %>%
            pivot_wider(names_from = variable, values_from = threshold)

world_indicators<- world %>%
                   select(-c(Unit, Meta)) %>%
                   filter(Region=="World"&Model!="Reference") %>%
                   mutate(Variable=str_replace_all(Variable,"[|/ ]", "_")) %>%
                   mutate(Variable=str_to_lower(Variable, locale = "en")) %>%
                   pivot_longer(-c(Model,Scenario, Region, Variable), names_to = "Year", values_to = "Value" ) %>% 
                   pivot_wider(id_cols=c(Model, Scenario, Region, Year), names_from = Variable, values_from = Value)%>% 
                   unite("Scenario_ID", Model:Scenario, remove = FALSE) %>%
                   filter(Year %in% years) %>%
                   mutate(Year=as.numeric(Year))

#merge with baselines
world_indicators<-left_join(world_indicators, baselines, by=c("Model", "Scenario"))
                  
indicators_no_baselines<-world_indicators %>%
                         filter(type=="mitigation")

#prepare meta
meta<-meta %>%
      select(model, scenario, category, marker) %>%
      rename(Model=model, Scenario=scenario)

indicators_no_baselines<-left_join(indicators_no_baselines, meta, by=c("Scenario", "Model"))



indicators_no_baselines<-indicators_no_baselines %>%
                         mutate(SSP_family=ifelse(grepl('SSP1', Scenario_ID), 1,
                                           ifelse(grepl('SSP2', Scenario_ID), 2,                                                                                       ifelse(grepl('SSP3', Scenario_ID), 3,
                                           ifelse(grepl('SSP4', Scenario_ID), 4,                                                                                       ifelse(grepl('SSP5', Scenario_ID), 5, 2                                                                        )))))) %>%
                        mutate(SSP_family=as.factor(SSP_family))

```


```{r indicators_economic, include=FALSE, MESSAGE=FALSE}

#Carbon Price
indicators_calculated<-indicators_no_baselines %>%
                       group_by(Scenario_ID) %>%
                       #we add 1 in case carbon price is zero
                       mutate(carbon_ratio=price_carbon/lag(price_carbon+1)) %>%
                       #carbon price net present value assuming 5 % discount rate
                       mutate(carbon_price_npv = price_carbon/(1.05^(Year-2020)))

#GDP loss and investments
gdp_investment_baselines<-world_indicators %>%
                          select(Model, Scenario, economic_baseline, gdp_ppp, investment_energy_supply, Year)%>%
                          filter(Scenario==economic_baseline) %>%
                          rename(gdp_ppp_b=gdp_ppp) %>%
                          rename(investment_energy_supply_b=investment_energy_supply) %>%
                          select(-Scenario)

indicators_calculated<-left_join(indicators_calculated,gdp_investment_baselines, by=c("Model", "economic_baseline", "Year"))

indicators_calculated<-indicators_calculated %>%
                       mutate(gdp_loss = (1-gdp_ppp/gdp_ppp_b)*100) %>%
                       #some models report GDP as zero when in fact it should be reported as missing 
                       mutate(gdp_loss=ifelse(gdp_loss==0, NA, gdp_loss)) %>%
                       mutate(invest_ratio = investment_energy_supply/investment_energy_supply_b)


#Stranded coal###
coal<-coal_50_all %>%
      filter(Region=="World") %>%
      select(-Region) %>%
      mutate(coal_electricity_50=coal_capacity_50*365*24*0.60*0.0000036)


indicators_calculated<-left_join(indicators_calculated, coal, by="Year")

indicators_calculated<-indicators_calculated %>%
                       mutate(coal_stranded1=(coal_electricity_50-secondary_energy_electricity_coal)/coal_electricity_50*100) %>%
                       group_by(Scenario_ID) %>%
                       mutate(coal_stranded2=coal_stranded1-lag(coal_stranded1)) %>%
                       mutate(coal_stranded2=ifelse(Year>=2070|coal_stranded2<0, 0, coal_stranded2)) %>%
                       mutate(coal_stranded2=ifelse(coal_stranded2>100, 100, coal_stranded2))
```


```{r indicators_technology, include=FALSE, MESSAGE=FALSE}
#Technological indicators###

indicators_calculated<-indicators_calculated %>%
                       ungroup() %>%
                       group_by(Scenario_ID) %>%
#electricity
mutate(coal_share=secondary_energy_electricity_coal/secondary_energy_electricity*100) %>%
mutate(coal_drop=lag(coal_share)-coal_share)%>%
mutate(wind_share=secondary_energy_electricity_wind/secondary_energy_electricity*100) %>%
mutate(wind_scale=(wind_share-lag(wind_share))) %>%
mutate(solar_share=secondary_energy_electricity_solar/secondary_energy_electricity*100) %>%
mutate(solar_scale=(solar_share-lag(solar_share))) %>%
mutate(nuclear_share=secondary_energy_electricity_nuclear/secondary_energy_electricity*100) %>%
mutate(nuclear_scale=(nuclear_share-lag(nuclear_share))) %>%
mutate(biomass_share=secondary_energy_electricity_biomass/secondary_energy_electricity*100) %>%
mutate(biomass_scale=(biomass_share-lag(biomass_share))) %>%
mutate(biomass_ccs=secondary_energy_electricity_biomass_w__ccs/secondary_energy_electricity*100) %>%
mutate(biomass_ccs_scale=(biomass_ccs-lag(biomass_ccs))) %>%
mutate(coal_ccs=secondary_energy_electricity_coal_w__ccs/secondary_energy_electricity*100) %>%
mutate(coal_ccs_scale=(coal_ccs-lag(coal_ccs))) %>%  
#transport
mutate(share_electricity_transport=final_energy_transportation_electricity/final_energy_transportation*100) %>%
mutate(transport_e_increase=share_electricity_transport-lag(share_electricity_transport)) %>%
mutate(share_biofuels=final_energy_transportation_liquids_biomass/final_energy_transportation*100) %>%
mutate(transport_bio_increase=share_biofuels-lag(share_biofuels)) %>%
#demand    
mutate(forest_increase=(land_cover_forest/lag(land_cover_forest)-1)*100) %>%
mutate(pasture_drop=(1-land_cover_pasture/lag(land_cover_pasture))*100) %>%
mutate(demand_drop=(1-final_energy/lag(final_energy))*100) %>%
mutate(demand_re_drop=(1-final_energy_residential_and_commercial/lag(final_energy_residential_and_commercial))*100) %>%
mutate(demand_transport_drop=(1-final_energy_transportation/lag(final_energy_transportation))*100) %>%
mutate(demand_industry_drop=(1-final_energy_industry_electricity/lag(final_energy_industry_electricity))*100) %>%
mutate(livestock_share=food_demand_livestock/food_demand*100) %>%
mutate(livestock_drop=lag(livestock_share)-livestock_share) %>%
mutate(neg_emissions_check = ifelse(emissions_co2<0,1,0))%>%
mutate(neg_emissions=emissions_co2*neg_emissions_check*(-1))%>%
mutate(neg_emissions_cum=cumsum(neg_emissions))

```

```{r indicators_governance, include=FALSE, MESSAGE=FALSE}

#merge governance data with regions
region_con<-region_con %>%
            rename(countrycode = iso)

governance_proj<-left_join(governance_proj, region_con, by="countrycode")

#aggregate governance levels by median
governance_proj_reg <- governance_proj %>%
                   group_by(scenario, regions, year) %>%
                   summarise_at(vars(gov), median) %>%
                   mutate(year=ifelse(year==2099,2100,year)) %>%
                   rename(Region=regions) %>%
                   rename(Year=year) %>%
                   rename(SSP_pred=scenario) %>%
                   ungroup()%>%
                   mutate(SSP_pred=as.numeric(str_replace_all(SSP_pred,"SSP", ""))) %>%
                   mutate(
                   Region = case_when(
                                    Region=="ASIA" ~ "R5ASIA", 
                                    Region=="LAM" ~ "R5LAM",
                                    Region=="OECD" ~ "R5OECD90+EU",
                                    Region=="REF" ~ "R5REF",
                                    Region=="MAF" ~ "R5MAF"
                                     ))

#Regional indicators for population and CO2 emissions
region_indicators<-region %>%
                   select(-c(Unit, Meta)) %>%
                   filter(Region!="World"&Region!="R5ROWO"&Model!="Reference") %>%
                   mutate(Variable=str_replace_all(Variable,"[|/ ]", "_")) %>%
                   mutate(Variable=str_to_lower(Variable, locale = "en")) %>%
                   pivot_longer(-c(Model,Scenario, Region, Variable), names_to = "Year", values_to = "Value" ) %>% 
                   pivot_wider(id_cols=c(Model, Scenario, Region, Year), names_from = Variable, values_from = Value)%>% 
                   unite("Scenario_ID", Model:Scenario, remove = FALSE) %>%
                   filter(Year %in% years) %>%
                   mutate(Year=as.numeric(Year)) %>%
                   mutate(SSP_pred=ifelse(grepl('SSP1', Scenario_ID), 1,
                                           ifelse(grepl('SSP2', Scenario_ID), 2,                                               ifelse(grepl('SSP3', Scenario_ID), 3,
                                           ifelse(grepl('SSP4', Scenario_ID), 4,                                               ifelse(grepl('SSP5', Scenario_ID), 5, 2                                                                        )))))) 

region_indicators<-left_join(region_indicators, governance_proj_reg, by=c("Year", "Region", "SSP_pred"))


#generating key indicators

region_indicators<-region_indicators %>%
                   group_by(Scenario_ID, Region) %>%
                   mutate(neg_emissions_check = ifelse(emissions_co2<0,1,0)) %>%
                   mutate(neg_emissions_abs=emissions_co2*neg_emissions_check*(-1)) %>% 
                   mutate(emissions_drop=abs((1-(abs(emissions_co2)/population)/lag(abs(emissions_co2)/population))*100)) %>%
           mutate(emissions_drop=ifelse(emissions_drop>100,100,emissions_drop))
  
neg_emissions_temp<-region_indicators %>% 
                    mutate(neg_emissions_year=ifelse(c(0,diff(sign(emissions_co2)))<0, 1,0)) %>%
                    filter(neg_emissions_year==1) %>%
                    select(-neg_emissions_year) %>%
                    rename(neg_emissions_year=Year) %>%
                    select(Scenario_ID, Region, neg_emissions_year)
  
region_indicators<-left_join(region_indicators, neg_emissions_temp, by=c("Scenario_ID", "Region"))

region_indicators<-left_join(region_indicators, meta, by=c("Model", "Scenario"))

region_indicators<- region_indicators %>% 
                    mutate(concern_governance=ifelse(gov<=0.6&emissions_drop>20, 3,
                    ifelse(gov>0.6&emissions_drop>20, 2,1)))


#governance world level

gov_world<-region_indicators %>%
  distinct(Scenario_ID, Year, .keep_all = TRUE) %>%
  group_by(Scenario_ID, Year) %>%
  summarise_at(vars(concern_governance), prod) %>%
  mutate(concern_governance=concern_governance^(1/5)) %>%
  mutate(Region="World") %>%
  select(-Region)

indicators_calculated<-left_join(indicators_calculated, gov_world, by=c("Year", "Scenario_ID"))

#write.csv(indicators_calculated,here("input", "indicators_calculated.csv"), row.names = F)

```

```{r indicators_thresholds, include=FALSE, MESSAGE=FALSE}

#first focus on economic concerns

e<-c("concern_gdp", "concern_carbon", "concern_investment", "concern_coal")


indicators_concerns<-indicators_calculated %>%
                     group_by(Scenario_ID, Year) %>%
                     mutate(concern_gdp=ifelse(gdp_loss>=thresholds$gdp_high,3, ifelse(gdp_loss<thresholds$gdp_low,1,2))) %>%
                     mutate(concern_carbon=ifelse(carbon_price_npv>=thresholds$carbon_high&carbon_ratio>=thresholds$carbon_ratio_high,3, 
                     ifelse(carbon_ratio<thresholds$carbon_ratio_high&carbon_price_npv<=thresholds$carbon_low,1,2))) %>%
                     mutate(concern_investment=ifelse(invest_ratio>=thresholds$invest_high,3,
                                ifelse(invest_ratio<thresholds$invest_high&invest_ratio>=thresholds$invest_low,2,1))) %>%
                     mutate(concern_coal=ifelse(coal_stranded2>=thresholds$coal_high,3,
                          ifelse(coal_stranded2<thresholds$coal_high&coal_stranded2>=thresholds$coal_low,2,1))) %>%
                     mutate(product_economic=prod(c(concern_gdp,concern_carbon,concern_investment,concern_coal), na.rm=TRUE))%>%
                     mutate(confidence_e=length(e)-sum(is.na(c(concern_gdp,concern_carbon,concern_investment,concern_coal))))%>%
                     mutate(confidence_econ=ifelse(confidence_e==0,1, ifelse(confidence_e>2,3,2)))%>%
                     mutate(concern_economic=product_economic^(1/confidence_e)) %>%
                     mutate(concern_economic=ifelse(confidence_e==0, NA, concern_economic))

#technology concerns

t<-c("concern_wind","concern_solar","concern_nuclear","concern_biomass","concern_biomass_ccs","concern_coal_ccs","concern_transport_e","concern_transport_bio")

indicators_concerns <-  indicators_concerns %>%
                        group_by(Scenario_ID, Year) %>%
                        #mutate(concern_neg_emissions=ifelse(neg_emissions>=thresholds$neg_high,3,
                        #ifelse(neg_emissions<thresholds$neg_high&neg_emissions>=thresholds$neg_low,2,1))) %>%
                        mutate(concern_wind=ifelse(wind_scale>=thresholds$wind_high, 3,
                            ifelse(wind_scale<thresholds$wind_high&wind_scale>=thresholds$wind_low,2,1))) %>%
                        mutate(concern_solar=ifelse(solar_scale>=thresholds$solar_high,3,
                             ifelse(solar_scale<thresholds$solar_high&solar_scale>=thresholds$solar_low,2,1))) %>%
                        mutate(concern_nuclear=ifelse(nuclear_scale>=thresholds$nuclear_high,3,
                               ifelse(nuclear_scale<thresholds$nuclear_high&nuclear_scale>=thresholds$nuclear_low,2,1))) %>%
                        mutate(concern_biomass=ifelse(biomass_scale>=thresholds$biomass_high,3,
                               ifelse(biomass_scale<thresholds$biomass_high&biomass_scale>=thresholds$biomass_low,2,1))) %>%
                        mutate(concern_biomass_ccs=ifelse(biomass_ccs_scale>=thresholds$biomass_css_high,3,
                                   ifelse(biomass_ccs_scale<thresholds$biomass_css_high&biomass_ccs_scale>=thresholds$biomass_css_low,2,1))) %>%
                        mutate(concern_coal_ccs=ifelse(coal_ccs_scale>=thresholds$coal_css_high,3,
                                ifelse(coal_ccs_scale<thresholds$coal_css_high&coal_ccs_scale>=thresholds$coal_css_low,2,1))) %>%
                        mutate(concern_transport_e=ifelse(transport_e_increase>=thresholds$tran_elec_high,3,
                                   ifelse(transport_e_increase<thresholds$tran_elec_high&transport_e_increase>=thresholds$tran_elec_low,2,1))) %>%
                        mutate(concern_transport_bio=ifelse(transport_bio_increase>=thresholds$tran_bio_high,3,
                                     ifelse(transport_bio_increase<thresholds$tran_bio_high&transport_bio_increase>=thresholds$tran_bio_low,2,1))) %>% 
                        mutate(product_technological=prod(c(concern_wind,concern_solar,concern_nuclear,concern_biomass, 
                                     concern_biomass_ccs, concern_coal_ccs,concern_transport_e,concern_transport_bio),na.rm=TRUE)) %>%
                        mutate(confidence_t=length(t)-sum(is.na(c(concern_wind,concern_solar,concern_nuclear,concern_biomass, 
                                      concern_biomass_ccs, concern_coal_ccs,concern_transport_e,concern_transport_bio)))) %>%
                        mutate(concern_tech=product_technological^(1/confidence_t))%>%
                        mutate(confidence_tech=ifelse(confidence_t==0,1, ifelse(confidence_t>7,3,2))) %>%
                        mutate(concern_tech=ifelse(confidence_t==0, NA, concern_tech))



#socio-technical concerns
s<-c("concern_livestock","concern_demand","concern_transport","concern_demand_re",
       "concern_demand_industry","concern_forest","concern_pasture")
  
indicators_concerns<-indicators_concerns %>%
    group_by(Scenario_ID, Year) %>%
    mutate(concern_livestock=ifelse(livestock_drop>=thresholds$livestock_high,3,
                                 ifelse(livestock_drop<thresholds$livestock_high&livestock_drop>=thresholds$livestock_low,2,1))) %>%
    mutate(concern_demand=ifelse(demand_drop>=thresholds$fe_demand_high,3,
                              ifelse(demand_drop<thresholds$fe_demand_high&demand_drop>=thresholds$fe_demand_low,2,1))) %>%
    mutate(concern_transport=ifelse(demand_transport_drop>=thresholds$tran_demand_high,3,
                                 ifelse(demand_transport_drop<thresholds$tran_demand_high&demand_transport_drop>=thresholds$tran_demand_low,2,1))) %>%
    mutate(concern_demand_re=ifelse(demand_re_drop>=thresholds$res_demand_high,3,
                                 ifelse(demand_re_drop<thresholds$res_demand_high&demand_re_drop>=thresholds$res_demand_low,2,1))) %>%
    mutate(concern_demand_industry=ifelse(demand_industry_drop>=thresholds$ind_demand_high,3,
                                       ifelse(demand_industry_drop<thresholds$ind_demand_high&demand_industry_drop>=thresholds$ind_demand_low,2,1))) %>%
    mutate(concern_forest=ifelse(forest_increase>=thresholds$forest_high,3,
                              ifelse(forest_increase<thresholds$forest_high&forest_increase>=thresholds$forest_low,2,1))) %>%
    mutate(concern_pasture=ifelse(pasture_drop>=thresholds$pasture_high,3,
                               ifelse(pasture_drop<thresholds$pasture_high&pasture_drop>=thresholds$pasture_low,2,1))) %>%
    mutate(product_social=prod(c(concern_livestock,concern_demand,concern_transport,concern_demand_re,
                              concern_demand_industry,concern_forest,concern_pasture),na.rm=TRUE)) %>%
    mutate(confidence_s=length(s)-sum(is.na(c(concern_livestock,concern_demand,concern_transport,concern_demand_re,
                                      concern_demand_industry,concern_forest,concern_pasture)))) %>%
    mutate(concern_social=product_social^(1/confidence_s))%>%
    mutate(confidence_soc=ifelse(confidence_s==0,1, ifelse(confidence_s>5,3,2))) %>%
    mutate(concern_social=ifelse(confidence_s==0, NA, concern_social))



#overall feasibility concerns
indicators_concerns<-indicators_concerns %>%
                     group_by(Scenario_ID, Year) %>%
                     mutate(concern_overall=prod(c(concern_governance,concern_economic,concern_tech, concern_social)^(1/4), na.rm = T))

```


```{r aggregation_dimensions,include=FALSE, MESSAGE=FALSE}

feasibility_agg<-indicators_concerns %>%
                 filter(Year>2020) %>%
                 ungroup() %>%
                 select(c(Scenario_ID)|starts_with("concern")) %>%
                 group_by(Scenario_ID) %>%
                 summarise_all(geom_mean) 

tem_category<-indicators_concerns %>%
              filter(Year==2030) %>%
              ungroup() %>%
              select(Scenario_ID, category, SSP_family)
        
feasibility_agg<-left_join(feasibility_agg, tem_category, by="Scenario_ID")

agg_1.5<-  feasibility_agg %>%
           filter(category %in% below_1.5) %>%
           filter(SSP_family==2) %>%
           select(Scenario_ID, concern_overall, concern_tech, concern_economic, concern_social, concern_governance) %>%
           rename(Overall=concern_overall) %>%
           rename(Technology=concern_tech) %>%
           rename(Economic=concern_economic) %>%
           rename(`Socio-cultural`=concern_social) %>%
           rename(Institutional=concern_governance) %>%
           pivot_longer(-c(Scenario_ID), names_to = "dimension", values_to = "feasibility_value" ) 

#Preparing data for the overviews over time

time_1.5<- indicators_concerns %>%
           filter(category %in% below_1.5) %>%
           filter(SSP_family==2) %>%
           select(c(Scenario_ID, Year, category)|starts_with("concern")) %>%
           rename(Overall=concern_overall) %>%
           rename(Technology=concern_tech) %>%
           rename(Economic=concern_economic) %>%
           rename(`Socio-cultural`=concern_social) %>%
           rename(Institutional=concern_governance) %>%
           pivot_longer(-c(Scenario_ID, Year, category), names_to = "dimension", values_to = "feasibility_value" ) 

meta_policy<-meta_policy %>%
            unite("Scenario_ID", Model:Scenario, remove = TRUE) %>%
            mutate(policy_simple=
                     ifelse(grepl('P2', Policy_category), "P2",
                          ifelse(grepl('P3',Policy_category), "P3",
                                Policy_category)))

time_1.5<-left_join(time_1.5, meta_policy, by="Scenario_ID")

time_all<- indicators_concerns %>%
           filter(SSP_family==2) %>%
           select(c(Scenario_ID, Year, category)|starts_with("concern")) %>%
           rename(Overall=concern_overall) %>%
           rename(Technology=concern_tech) %>%
           rename(Economic=concern_economic) %>%
           rename(`Socio-cultural`=concern_social) %>%
           rename(Institutional=concern_governance) %>%
           pivot_longer(-c(Scenario_ID, Year, category), names_to = "dimension", values_to = "feasibility_value" ) 

#Preparing data for the marker scenarios

overall_ips<-indicators_concerns %>%
             select(Model, Scenario, Year, concern_overall, concern_governance, concern_social, concern_tech, concern_economic)

overall_ips<-left_join(overall_ips, marker_set, by=c("Scenario", "Model"))

overall_ips<-overall_ips %>%
             filter(!is.na(marker))

```




## Figures in the main paper

```{r Figure2, echo=FALSE, warning=F, include=TRUE, MESSAGE=F, fig.width=14, fig.height=10,fig.cap="Aggregation over feasibility dimensions", fig.align="center", fig.topcaption=TRUE}

violin<-agg_1.5 %>%
  rename(`Feasibility concerns`=feasibility_value) %>%
  drop_na() %>%
  ggplot( aes(x=`Feasibility concerns`, y=dimension, fill=stat(x)))+
  geom_density_ridges_gradient(scale = 1,  
                               jittered_points = TRUE,
    position = position_points_jitter(height = 0),
    point_shape = '_', point_size = 3, point_alpha = 1) +
  scale_fill_gradient(low="#4DBBD5FF", high="#E64B3599", name = "Feasibility concerns")+
  theme_ipsum() +
  ggtitle("Feasibility Concerns (2020-2100) - SSP2 - All below 1.5 C") +
  xlab("Increasing Feasibility Concerns")+
  ylab("")+
  scale_y_discrete(limits=c("Technology","Economic","Socio-cultural","Institutional", "Overall"))+
  coord_flip()+
  theme(axis.title.y = element_text(size=18), axis.title.x = element_text(size=16))+
  theme(axis.text.x = element_text(size=20, face = "bold"), axis.title.y = element_text(size=20), legend.text = element_text(size = 20))
  
violin

ggsave(here("figures", "figure2_paper.png"), units="in", width=16, height=10, dpi=300)

```



```{r Figure3, echo=FALSE, warning=F, include=TRUE, MESSAGE=F, fig.width=14, fig.height=10,fig.cap="Aggregation over feasibility dimensions", fig.align="center", fig.topcaption=TRUE}

plot_region<-region_indicators %>%
  filter(Year>2010) %>%
  filter(category %in% below_1.5) %>%
  filter(SSP_pred==2) %>%  
  ggplot(aes(x=Year, y=concern_governance, colour=Region, fill=Region))+
  theme(text = element_text(size = 14), angle=90)+
  stat_smooth(size=2, span=0.5, se=F)+
  theme_ipsum()+ 
   xlab("")+
  ylab("Increasing Feasibility Concerns")+
    scale_color_uchicago() +
    scale_fill_uchicago()+
     theme(axis.title.y = element_text(size=20), legend.text = element_text(size = 20), legend.position = c(0.8,0.8))+
  ggtitle("Institutional Feasibility Concerns - SSP2 - Reaching 1.5C - Across Regions")

plot_region

ggsave(here("figures", "figure3_paper.png"), units="in", width=14, height=7, dpi=300)

```


```{r Figure4, echo=FALSE, warning=F, include=TRUE, MESSAGE=F, fig.width=14, fig.height=10,fig.cap="Aggregation over feasibility dimensions", fig.align="center", fig.topcaption=TRUE}

plot_category<-time_all %>%
  rename(`Level of concern`=feasibility_value) %>%
  filter(Year>2010) %>%
  filter(category!="no-climate-assessment") %>%
  filter(category!="Above 2C") %>%
  filter(dimension=="Overall") %>%
  mutate(category=factor(category,levels=c("1.5C low overshoot", "1.5C high overshoot","Lower 2C", "Higher 2C"))) %>%
  drop_na() %>%
  ggplot(aes(x=Year, y=`Level of concern`, color=category, fill=category))+
  geom_smooth(size=2, span=0.4, se=F)+
  theme_ipsum() +
  ylab("Increasing Feasibility Concerns")+
  xlab("")+
  scale_color_manual(values = c("#00A08799",
                                "#4DBBD599",
                                "#8491B499",
                                "#F39B7F99",
                                "#E64B3599"),
                     breaks = c("Below 1.5C", "1.5C low overshoot", "1.5C high overshoot","Lower 2C", "Higher 2C")) +
   scale_fill_manual(values = c("#00A08799",
                                "#4DBBD599",
                                "#8491B499",
                                "#F39B7F99",
                                "#E64B3599"),
                     breaks = c("Below 1.5C", "1.5C low overshoot", "1.5C high overshoot","Lower 2C", "Higher 2C"))+
   ylim(1, 1.35)+
     theme(axis.title.y = element_text(size=20), legend.text = element_text(size = 15), legend.position = c(0.8,0.8))+
  labs(fill = "Climate categories", color="Climate categories")



 plot_delay<-time_1.5 %>%
  rename(`Level of concern`=feasibility_value) %>%
  filter(Year>2010) %>%
  filter(category!="Below 1.5C") %>%
  drop_na() %>%
   filter(policy_simple!="P???") %>%
   filter(dimension=="Overall") %>%
  ggplot(aes(x=Year, y=`Level of concern`, colour=policy_simple, label=Scenario_ID, fill=policy_simple))+
  stat_smooth(size=2, se=F, span=0.5)+
  theme_ipsum()+ 
  xlab("")+
  scale_color_manual(values = c( "#00A08799",
                                "gray"),name="Policy category", 
                      labels=c("Immediate Policy Action (2020)", "Delayed Policy Action (2030)"))+
  scale_fill_manual(values = c("#00A08799",
                                "gray"), 
                      name="Policy category", 
                      labels=c("Immediate Policy Action (2020)", "Delayed Policy Action (2030)"))+
  ylim(1,1.5)+
  ylab("")+
  theme(axis.title.y = element_text(size=20), legend.text = element_text(size = 15), legend.position = c(0.8,0.8))
 


plot_time_trade_off<-plot_grid(plot_category, plot_delay, labels = "AUTO" ) 

plot_time_trade_off

ggsave(here("figures", "figure4_paper.png"), units="in", width=14, height=7, dpi=300)
```

```{r Figure5, echo=FALSE, warning=F, include=TRUE, MESSAGE=F, fig.width=14, fig.height=10,fig.cap="Aggregation over feasibility dimensions", fig.align="center", fig.topcaption=TRUE}

 plot_ips<-overall_ips %>%
  filter(Year>2010) %>%
  mutate(ip_label=ifelse(Year==2100,marker, NA)) %>%
  mutate(marker=ifelse(marker=="LED", "LED/P1", marker)) %>%
  mutate(marker=ifelse(marker=="S1", "S1/P2", marker)) %>%
  mutate(marker=ifelse(marker=="S2", "S2/P3", marker)) %>%
  mutate(marker=ifelse(marker=="S5", "S5/P4", marker)) %>%
  mutate(ip_label=ifelse(ip_label=="LED", "LED/P1", ip_label)) %>%
  mutate(ip_label=ifelse(ip_label=="S1", "S1/P2", ip_label)) %>%
  mutate(ip_label=ifelse(ip_label=="S2", "S2/P3", ip_label)) %>%
  mutate(ip_label=ifelse(ip_label=="S5", "S5/P4", ip_label)) %>%

  ggplot(aes(x=Year, y=concern_overall, colour=marker, linetype=marker))+
  geom_smooth(size=2, span=0.5)+
  scale_color_manual(values = c("LED/P1" = "#00A087FF", "S1/P2" = "#4DBBD5FF", 
                                 "S2/P3"="#8491B4FF", "S5/P4"="#F39B7FFF"))+
  geom_text_repel(aes(label=ip_label),
    force             = 3,
    nudge_x           = 0.30,
    direction         = "y",
    hjust             = 0,
    segment.size      = 0.6,
    segment.curvature = -0.3)+
    ylim(1,1.7)+
    theme_ipsum()+ 
    xlab("")+
    ylab("Increasing feasibility concerns")+
   scale_x_continuous(breaks=seq(2020,2100,10))+
  theme(axis.title.y = element_text(size=18), axis.title.x = element_text(size=16), legend.position="none")
 
plot_ips

ggsave(here("figures", "figure5_paper.png"), units="in", width=10, height=5, dpi=300)

```